version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
          MYSQL_USERNAME: 'root'
          MYSQL_PASSWORD: 'password'
      - image: circleci/mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_DATABASE: what_app_test
      - image: selenium/standalone-chrome:latest

    working_directory: ~/what_app

    steps:
      - checkout

      - restore_cache:
          keys:
            - what_app-bundle-v1-{{ checksum "Gemfile.lock" }}
            - what_app-bundle-v1-
      - run:
          name: Bundlerをinstall
          command: |
            gem update --system
            gem install bundler
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: what_app-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          keys:
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
            - rails-demo-yarn-
      - run:
          name: Yarnをinstall
          command: yarn install --cache-folder ~/.cache/yarn
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run: bundle exec bin/webpack
      - run:
          name: helpersスペック
          command: bundle exec rspec spec/helpers
      - run:
          name: modelスペック
          command: bundle exec rspec spec/models
      - run:
          name: requestスペック
          command: bundle exec rspec spec/requests
      - run:
          name: systemスペック(コメント)
          command: bundle exec rails db:environment:set RAILS_ENV=test
          command: bundle exec rspec spec/systems/comments_spec.rb
      - run:
          name: systemスペック(いいね)
          command: bundle exec rails db:environment:set RAILS_ENV=test
          command: bundle exec rspec spec/systems/favorite_relationships_spec.rb
      - run:
          name: systemスペック(記事投稿)
          command: bundle exec rails db:environment:set RAILS_ENV=test
          command: bundle exec rspec spec/systems/microposts_spec.rb
      - run:
          name: systemスペック(通知機能)
          command: bundle exec rails db:environment:set RAILS_ENV=test
          command: bundle exec rspec spec/systems/notifications_spec.rb
      - run:
          name: systemスペック(パスワード変更)
          command: bundle exec rails db:environment:set RAILS_ENV=test
          command: bundle exec rspec spec/systems/password_edits_spec.rb
      - run:
          name: systemスペック(フォロー機能)
          command: bundle exec rails db:environment:set RAILS_ENV=test
          command: bundle exec rspec spec/systems/relationship_spec.rb
      - run:
          name: systemスペック(検索機能)
          command: bundle exec rails db:environment:set RAILS_ENV=test
          command: bundle exec rspec spec/systems/searches_spec.rb
      - run:
          name: systemスペック(ログイン)
          command: bundle exec rails db:environment:set RAILS_ENV=test
          command: bundle exec rspec spec/systems/users_login_spec.rb
      - run:
          name: systemスペック(新規登録)
          command: bundle exec rails db:environment:set RAILS_ENV=test
          command: bundle exec rspec spec/systems/users_signup_spec.rb
      - run:
          name: run rubocop
          command: bundle exec rubocop
      - store_test_results:
          path: /tmp/test-results